import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";
import GlobalProvider from "../context/GlobalProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bike Station",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <Providers>
            <Navbar />
            <main>{children}</main>
            <Toaster position="bottom-right" />
          </Providers>
        </GlobalProvider>
      </body>
    </html>
  );
}
